#!/usr/bin/env python3
"""Generates src/unicode.zig, the general category ranges used by regex \\p{...}."""
import sys
try:
    import unicodedata2 as unicodedata
except ImportError:
    import unicodedata
from pathlib import Path

ranges = {}
for cp in range(0x110000):
    category = unicodedata.category(chr(cp))
    spans = ranges.setdefault(category, [])
    if spans and spans[-1][1] == cp - 1:
        spans[-1][1] = cp
    else:
        spans.append([cp, cp])

lines = [
    f"//! Generated by scripts/unicode.py from Unicode {unicodedata.unidata_version}. Do not edit.",
    "",
    "pub const categories = .{",
]
for category in sorted(ranges):
    body = ", ".join(f".{{ 0x{lo:X}, 0x{hi:X} }}" for lo, hi in ranges[category])
    lines.append(f'    .{{ "{category}", &[_][2]u21{{ {body} }} }},')
lines.append("};")
Path(__file__).parent.parent.joinpath("src/unicode.zig").write_text("\n".join(lines) + "\n")
